### PR TITLE
AMQNET-565 NetStandard 2.0 Build

### PR DESCRIPTION
**Pull request by michaelandrepearce**
This is to provide a netstandard2.0 build that will also publish to nuget.

### CODE REVIEW

**Comment by michaelandrepearce** [comment]
@killnine and @artnaseef we can do refactors later, this just unblocks and gets ball rolling with getting a netstandard 2.0 build which then is compatible with net 4.6 and core 2.0. 
Note only a few changes in tests to update them to make compatible, else it justs builds whats there.

**Comment by killnine** [comment]
Sounds good!

**Comment by michaelandrepearce** [comment]
This is starting to block work on NMS AMQP, currently no objections, will look to merge soon @artnaseef any chance you could look at this?

**Comment by michaelandrepearce** [comment]
Will merge this tomorrow morning uk time. As no other comments

**Comment by cjwmorgan-sol** [comment]
The build for the netstandard 2.0 looks great the generated nuget package does not have the older framework libraries so it will likely need some further work to "add Netstandard 2.0" alongside the other frameworks that 1.7.1 supports.

I couldn't really find how the old nuget package gets created by checking the nant scripts, however looking at the nuget package downloaded from nuget.org I saw the 1.7.1 package supports the following frameworks: net20, net20-cf, net35, and net40.

**Comment by michaelandrepearce** [comment]
@cjwmorgan-sol if you want the older you build using the exisiting prj and slns. We havent touched those this just provides an additional build. Stuff in nuget hasnt been published there by apache project. We have no control. We will look to publish the .net core build there though

**Comment by cjwmorgan-sol** [comment]
@michaelandrepearce thanks, I was under the impression that, https://www.nuget.org/packages/Apache.NMS/, was added to nuget.org with the blessing of the apache project. 

Since there is no previous official package I don't see any issue with the generated nuget package. This looks great!

**Pull request merged**
