### PR TITLE
AMQNET-745 fixed NRE for single file assembly

### PR DESCRIPTION
**Pull request by i7nfinity**

### CODE REVIEW

**Comment by michaelpearce-gain** [comment]
@lukeabsent / @HavretGC does this make sense, have you seen this for review?

**Comment by Havret** [comment]
@i7nfinity could you please provide minimal reproducible example app so we can verify your fix, thanks?

**Comment by i7nfinity** [comment]
> could you please provide a minimal reproducible example app so we can verify your fix, thanks?

An example is posted here https://github.com/i7nfinity/apache-nms-singlefile-error
If run this script https://github.com/i7nfinity/apache-nms-singlefile-error/blob/main/src/ApacheNmsSingleAppError/build.sh
then you can see the error for PublishSingleFile=true

**Review by Havret — APPROVED** [review]
LGTM. It need to be ported to 1.8.0. In future me should consider switching to `AppContext.BaseDirectory`.

**Pull request merged**
